<?php

namespace AppBundle\Repository;

/**
 * Client_orderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Client_orderRepository extends \Doctrine\ORM\EntityRepository
{
}
