<?php

namespace AppBundle\Repository;

/**
 * Order_elementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Order_elementRepository extends \Doctrine\ORM\EntityRepository
{
}
